apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-cronjob
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 300  # Максимальная задержка запуска - 5 минут
  concurrencyPolicy: Forbid     # Запрещаем параллельное выполнение
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Удалить Job спустя 24 часа после завершения
      activeDeadlineSeconds: 600  # Максимальное время выполнения - 10 минут
      template:
        spec:
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "FALSE"
            - name: ALLOWED_HOSTS
              value: "*"
          restartPolicy: OnFailure
