apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-cronjob
spec:
  schedule: "0 2 * * *"  # Каждый день в 2:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "FALSE"
            - name: ALLOWED_HOSTS
              value: "*"
          restartPolicy: OnFailure
