apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: django_app:latest
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY
        - name: DEBUG
          value: "FALSE"
        - name: ALLOWED_HOSTS
          value: "*"
      restartPolicy: Never
  backoffLimit: 3
